//Remove better weaponry weapons

ServerEvents.recipes(event => {
    event.remove({ output: 'better_weaponry:wooden_scythe'})
    event.remove({ output: 'better_weaponry:stone_scythe'})
    event.remove({ output: 'better_weaponry:golden_scythe'})
    event.remove({ output: 'better_weaponry:diamond_scythe'})
    event.remove({ output: 'better_weaponry:netherite_scythe'})

    event.remove({ output: 'better_weaponry:wooden_knife'})
    event.remove({ output: 'better_weaponry:stone_knife'})
    event.remove({ output: 'better_weaponry:golden_knife'})
    event.remove({ output: 'better_weaponry:diamond_knife'})
    event.remove({ output: 'better_weaponry:netherite_knife'})

    event.remove({ output: 'better_weaponry:wooden_rapier'})
    event.remove({ output: 'better_weaponry:stone_rapier'})
    event.remove({ output: 'better_weaponry:golden_rapier'})
    event.remove({ output: 'better_weaponry:diamond_rapier'})
    event.remove({ output: 'better_weaponry:netherite_rapier'})

    event.remove({ output: 'better_weaponry:wooden_glaive'})
    event.remove({ output: 'better_weaponry:stone_glaive'})
    event.remove({ output: 'better_weaponry:golden_glaive'})
    event.remove({ output: 'better_weaponry:diamond_glaive'})
    event.remove({ output: 'better_weaponry:netherite_glaive'})

    event.remove({ output: 'better_weaponry:wooden_cutlass'})
    event.remove({ output: 'better_weaponry:stone_cutlass'})
    event.remove({ output: 'better_weaponry:golden_cutlass'})
    event.remove({ output: 'better_weaponry:diamond_cutlass'})
    event.remove({ output: 'better_weaponry:netherite_cutlass'})

    event.remove({ output: 'better_weaponry:wooden_mace'})
    event.remove({ output: 'better_weaponry:stone_mace'})
    event.remove({ output: 'better_weaponry:copper_mace'})
    event.remove({ output: 'better_weaponry:golden_mace'})
    event.remove({ output: 'better_weaponry:diamond_mace'})
    event.remove({ output: 'better_weaponry:netherite_mace'})

    event.remove({ output: 'better_weaponry:wooden_chakram'})
    event.remove({ output: 'better_weaponry:stone_chakram'})
    event.remove({ output: 'better_weaponry:golden_chakram'})
    event.remove({ output: 'better_weaponry:diamond_chakram'})
    event.remove({ output: 'better_weaponry:netherite_chakram'})

    event.remove({ output: 'better_weaponry:wooden_claymore'})
    event.remove({ output: 'better_weaponry:stone_claymore'})
    event.remove({ output: 'better_weaponry:copper_claymore'})
    event.remove({ output: 'better_weaponry:golden_claymore'})
    event.remove({ output: 'better_weaponry:diamond_claymore'})
    event.remove({ output: 'better_weaponry:netherite_claymore'})

    event.remove({ output: 'better_weaponry:wooden_hammer'})
    event.remove({ output: 'better_weaponry:stone_hammer'})
    event.remove({ output: 'better_weaponry:golden_hammer'})
    event.remove({ output: 'better_weaponry:diamond_hammer'})
    event.remove({ output: 'better_weaponry:netherite_hammer'})

    event.remove({ output: 'better_weaponry:copper_pickaxe'})
    event.remove({ output: 'better_weaponry:copper_axe'})
    event.remove({ output: 'better_weaponry:copper_shovel'})
    event.remove({ output: 'better_weaponry:copper_hoe'})
    event.remove({ output: 'better_weaponry:copper_sword'})
    event.remove({ output: 'better_weaponry:copper_armor_helmet'})
    event.remove({ output: 'better_weaponry:copper_armor_chestplate'})
    event.remove({ output: 'better_weaponry:copper_armor_leggins'})
    event.remove({ output: 'better_weaponry:copper_armor_boots'})
})