//Remove epic knights weapons

ServerEvents.recipes(event => {
    event.remove({ output: 'epic_knights_ores_and_alloys:copper_pickaxe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:copper_axe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:copper_shovel'})
    event.remove({ output: 'epic_knights_ores_and_alloys:copper_hoe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:copper_sword'})

    event.remove({ output: 'epic_knights_ores_and_alloys:silver_pickaxe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_axe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_shovel'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_hoe'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_sword'})

    event.remove({ output: 'bronzeaddition_epicknights:bronze_hoe'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_axe'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_pickaxe'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_shovel'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_sword'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_armor_helmet'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_armor_chestplate'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_armor_leggins'})
    event.remove({ output: 'bronzeaddition_epicknights:bronze_armor_boots'})

    event.remove({ output: 'bronzeaddition_epicknights:steel_hoe'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_axe'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_pickaxe'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_shovel'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_sword'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_armor_helmet'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_armor_chestplate'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_armor_leggins'})
    event.remove({ output: 'bronzeaddition_epicknights:steel_armor_boots'})
})