ServerEvents.recipes(event => {
    event.remove({ output: 'useless_sword:silvillager'})
    event.remove({ output: 'galosphere:deepslate_silver_ore'})
    event.remove({ output: 'iceandfire:deepslate_silver_ore'})
    event.remove({ output: 'samurai_dynasty:deepslate_silver_ore'})
    event.remove({ output: 'samurai_dynasty:silver_block'})
    event.remove({ output: 'samurai_dynasty:steel_block'})
    event.remove({ output: 'eidolon:deep_silver_ore'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_ore'})
    event.remove({ output: 'epic_knights_ores_and_alloys:silver_block'})
    event.remove({ output: 'bronzeaddition_epicknights:eka_bronze_blockl'})
})