
["Materials Config"]

	#Changing armor and tools values requires game restart
	["Materials Config".blatium]

		["Materials Config".blatium.armor]
			values = [10, 14, 13, 10]
			toughness = 4
			knockbackResistance = 3.5

		["Materials Config".blatium.sword]
			damage = 25
			speed = -2.4

		["Materials Config".blatium.pickaxe]
			damage = 8
			destroyTime = 10.0
			speed = -2.8

		["Materials Config".blatium.axe]
			damage = 35
			speed = -3.0

		["Materials Config".blatium.hoe]
			damage = 8
			speed = 0.0

		["Materials Config".blatium.shovel]
			damage = 8
			speed = -3.0

	["Materials Config".nlium]

		["Materials Config".nlium.armor]
			values = [20, 27, 25, 20]
			toughness = 5
			knockbackResistance = 5.0

		["Materials Config".nlium.sword]
			damage = 45
			speed = -2.4

		["Materials Config".nlium.pickaxe]
			damage = 12
			destroyTime = 20.0
			speed = -2.8

		["Materials Config".nlium.axe]
			damage = 55
			speed = -3.0

		["Materials Config".nlium.hoe]
			damage = 12
			speed = 0.0

		["Materials Config".nlium.shovel]
			damage = 12
			speed = -3.0

